name: Test

on:
  push:
    branches-ignore:
      - main
      - prod
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Type Check
        run: npm run type-check

      - name: Run Tests
        run: npm test
        env:
          CI: true

      - name: Build Package
        run: npm run build

      - name: Verify Package Contents
        run: npm pack --dry-run